#!/bin/bash
echo "🎯 Pour télécharger votre avatar :"
echo ""
echo "1. Retournez au début de notre conversation"
echo "2. Trouvez l'image d'avatar (garçon avec sweat bordeaux)"
echo "3. Clic droit > Enregistrer l'image"
echo "4. Puis exécutez :"
echo ""
echo "   cp ~/Downloads/votre-image.png /home/user/JEUTAIME/public/demo-avatar.png"
echo ""
echo "5. Vérifiez que le fichier n'est pas vide :"
echo ""  
echo "   ls -lh /home/user/JEUTAIME/public/demo-avatar.png"
echo "   (doit afficher une taille > 0, par ex: 50K ou 100K)"
